approvedGitRepositories:
  - "**"
enableGlobalCache: false
enableScripts: true
npmMinimalAgeGate: 0
packageExtensions:
  "@oxc-parser/binding-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "*"
      "@emnapi/runtime": "*"
